coverage:
    status:
      project:
        default:
          informational: true
          target: auto
          threshold: 100%
      patch:
        default:
          informational: true
          target: auto
          threshold: 100%

comment:
    layout: "reach,diff,flags,files,footer"
    behaviour: default
    require_changes: no