
name: Test
on: pull_request
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
            fetch-depth: 2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
      - name: Run coverage
        run: go test -race -coverprofile=coverage.txt -covermode=atomic
      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash)
  
    #   - name: Lint
    #     uses: golangci/golangci-lint-action@v2
    #     with:
    #       version: v1.31
    #       args: --deadline=30m

    #   - name: Upload code coverage
    #     uses: codecov/codecov-action@v1