
name: Test
on: pull_request
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

    #   - name: Lint
    #     uses: golangci/golangci-lint-action@v2
    #     with:
    #       version: v1.31
    #       args: --deadline=30m

      - name: Upload code coverage
        uses: codecov/codecov-action@v1
        with:
          files: ./coverage.txt